export const siteConfig = {
    title: 'klanservicehub',
    description: 'Enterprise project management, issue tracking, and team collaboration suite.',
    keywords: [
        'reactjs',
        'nextjs',
        'appwrite',
        'appwrite-io',
        'next-auth',
        'react-big-calendar',
        'lucide-icons',
        'react-icons',
        'react-day-picker',
        'shadcn-ui',
        'radix-ui',
        'tailwindcss',
        'lodash',
        'react-query',
        'nuqs',
        'sonner',
        'typescript',
        'javascript',
        'vercel',
        'postcss',
        'prettier',
        'eslint',
        'react-dom',
        'html',
        'css',
        'nuqs-state-management',
        'infinite-query',
        'real-time-features',
        'organized-table',
        'filter-table',
        'paginate-table',
        'tasks-management',
        'projects-management',
        'workspaces-management',
        'ui/ux',
        'appwrite-db',
        'jira-clone',
        'date-fns',
        'cn',
        'clsx',
        'lucide-react',
    ],
    authors: {
        name: 'Ramakrishna K (RK)',
        url: 'https://ramakrishna3488.github.io/',
        github: 'https://github.com/RAMAKRISHNA3488',
        linkedin: 'https://www.linkedin.com/in/ramakrishna-k-a9a9811ab/',
        instagram: 'https://www.instagram.com/k_ramakrishna_99/',
    },
};
export const links = {
    sourceCode: 'https://github.com/RAMAKRISHNA3488',
    portfolio: 'https://ramakrishna3488.github.io/',
    linkedin: 'https://www.linkedin.com/in/ramakrishna-k-a9a9811ab/',
    instagram: 'https://www.instagram.com/k_ramakrishna_99/',
};